name: yacht_reservation_frontend
description: "Flutter app for yacht reservation system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # State Management
  flutter_bloc: ^9.1.1
  go_router: ^15.1.1

  # Network & JSON
  dio: ^5.8.0+1
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.5.3

  # Utilities
  logger: ^2.5.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
